workflows:
  ios-app-store:
    name: iOS App Store Build
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "Codemagic Upload"
    environment:
      groups:
        - ios_certs
      node: latest
      java: 21
      xcode: latest
    scripts:
      - name: Install Node modules
        script: npm install
      - name: Update Capacitor
        script: npx cap sync ios
      - name: Inject iOS Entitlements (Apple Sign In & Push)
        script: |
          cat << 'EOF' > ios/App/App/App.entitlements
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.developer.applesignin</key>
              <array>
                  <string>Default</string>
              </array>
              <key>aps-environment</key>
              <string>production</string>
          </dict>
          </plist>
          EOF
          sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Development";/CODE_SIGN_IDENTITY = "Apple Distribution"; CODE_SIGN_ENTITLEMENTS = App\/App.entitlements;/g' ios/App/App.xcodeproj/project.pbxproj
      - name: Set up keychain
        script: keychain initialize
      - name: Set up Provisioning Profile
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo $CM_PROVISIONING_PROFILE | base64 --decode > "$PROFILE_PATH"
      - name: Add Certificate to keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
      - name: Use profiles
        script: xcode-project use-profiles
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "ios/App/App.xcodeproj" \
            --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
  android-debug-build:
    name: Android Debug APK
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 21
    scripts:
      - name: Install Node modules
        script: npm install
      - name: Update Capacitor
        script: npx cap sync android
      - name: Build Android debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk

