drop extension if exists "pg_net";

create extension if not exists "pg_trgm" with schema "public";


  create table "public"."ai_logs" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "created_at" timestamp with time zone not null default now(),
    "club_id" uuid not null,
    "user_id" uuid,
    "prompt" text not null,
    "response" text,
    "tool_calls" jsonb default '[]'::jsonb,
    "metadata" jsonb default '{}'::jsonb,
    "rating" smallint,
    "feedback_note" text,
    "is_reviewed" boolean default false,
    "is_hallucination" boolean default false
      );


alter table "public"."ai_logs" enable row level security;


  create table "public"."clubs" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "slug" text not null,
    "logo_url" text,
    "primary_color" text default '#3b82f6'::text,
    "created_at" timestamp with time zone default now(),
    "default_casual_fee" numeric default 15.00,
    "default_member_fee" numeric default 10.00,
    "currency" text default 'AUD'::text,
    "contact_email" text,
    "website_url" text,
    "expense_label" text default 'Match Fees'::text,
    "income_label" text default 'Player Payments'::text,
    "theme_color" text default '#004d2c'::text,
    "secondary_color" text default '#ffffff'::text,
    "font_family" text default 'Inter'::text,
    "custom_domain" text,
    "season_name" text default 'Winter 2026'::text,
    "season_start" date,
    "season_end" date,
    "theme_font" text default 'Inter'::text,
    "square_access_token" text,
    "square_location_id" text,
    "is_square_enabled" boolean default false,
    "default_umpire_fee" numeric default 70,
    "sport_type" text default 'cricket'::text,
    "terminology_preset" jsonb default '{"role": "Captain", "unit": "Match", "expense": "Umpire Fee"}'::jsonb
      );


alter table "public"."clubs" enable row level security;


  create table "public"."fixtures" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "club_id" uuid,
    "team_id" uuid,
    "opponent" text not null,
    "match_date" date not null,
    "is_locked" boolean default false,
    "created_at" timestamp with time zone default now(),
    "umpire_fee" numeric default '75'::numeric,
    "announcement_notes" text,
    "match_time" time without time zone,
    "start_time" text,
    "location" text,
    "notes" text,
    "ai_reports_generated" numeric default '0'::numeric,
    "status" text default 'scheduled'::text
      );


alter table "public"."fixtures" enable row level security;


  create table "public"."match_reports" (
    "id" uuid not null default gen_random_uuid(),
    "fixture_id" uuid not null,
    "character_used" text not null,
    "report_text" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."match_reports" enable row level security;


  create table "public"."match_squads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "fixture_id" uuid,
    "player_id" uuid
      );


alter table "public"."match_squads" enable row level security;


  create table "public"."players" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "club_id" uuid,
    "default_team_id" uuid,
    "first_name" text not null,
    "last_name" text not null,
    "is_member" boolean default true,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid,
    "email" text,
    "nickname" text,
    "mobile_number" text
      );


alter table "public"."players" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text not null,
    "full_name" text,
    "updated_at" timestamp with time zone default now(),
    "role" text,
    "has_onboarded" boolean default false
      );


alter table "public"."profiles" enable row level security;


  create table "public"."teams" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "club_id" uuid,
    "name" text not null,
    "created_at" timestamp with time zone default now(),
    "member_fee" numeric default '10'::numeric,
    "casual_fee" numeric default '25'::numeric,
    "primary_color" text,
    "season_start" date,
    "season_end" date
      );


alter table "public"."teams" enable row level security;


  create table "public"."transactions" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "club_id" uuid,
    "player_id" uuid,
    "team_id" uuid,
    "fixture_id" uuid,
    "amount" numeric(10,2) not null,
    "transaction_type" text not null,
    "payment_method" text,
    "created_at" timestamp with time zone default now(),
    "description" text
      );


alter table "public"."transactions" enable row level security;


  create table "public"."user_roles" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "email" text not null,
    "club_id" uuid,
    "team_id" uuid,
    "role" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "can_take_payments" boolean default false
      );


alter table "public"."user_roles" enable row level security;


  create table "public"."users_deprecated_april2026" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "auth_id" uuid,
    "club_id" uuid,
    "role" text not null,
    "pin" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."users_deprecated_april2026" enable row level security;

CREATE UNIQUE INDEX ai_logs_pkey ON public.ai_logs USING btree (id);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX clubs_slug_key ON public.clubs USING btree (slug);

CREATE UNIQUE INDEX fixtures_pkey ON public.fixtures USING btree (id);

CREATE INDEX idx_fixtures_team_id ON public.fixtures USING btree (team_id);

CREATE INDEX idx_players_club_id ON public.players USING btree (club_id);

CREATE INDEX idx_teams_club_id ON public.teams USING btree (club_id);

CREATE INDEX idx_transactions_club_id ON public.transactions USING btree (club_id);

CREATE INDEX idx_transactions_player_id ON public.transactions USING btree (player_id);

CREATE INDEX idx_transactions_team_id ON public.transactions USING btree (team_id);

CREATE INDEX idx_user_roles_email ON public.user_roles USING btree (email);

CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);

CREATE UNIQUE INDEX match_reports_fixture_id_key ON public.match_reports USING btree (fixture_id);

CREATE UNIQUE INDEX match_reports_pkey ON public.match_reports USING btree (id);

CREATE UNIQUE INDEX match_squads_pkey ON public.match_squads USING btree (id);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX transactions_pkey ON public.transactions USING btree (id);

CREATE UNIQUE INDEX unique_club_user ON public.players USING btree (club_id, user_id);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users_deprecated_april2026 USING btree (id);

alter table "public"."ai_logs" add constraint "ai_logs_pkey" PRIMARY KEY using index "ai_logs_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."fixtures" add constraint "fixtures_pkey" PRIMARY KEY using index "fixtures_pkey";

alter table "public"."match_reports" add constraint "match_reports_pkey" PRIMARY KEY using index "match_reports_pkey";

alter table "public"."match_squads" add constraint "match_squads_pkey" PRIMARY KEY using index "match_squads_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."transactions" add constraint "transactions_pkey" PRIMARY KEY using index "transactions_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."users_deprecated_april2026" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."ai_logs" add constraint "ai_logs_rating_check" CHECK ((rating = ANY (ARRAY['-1'::integer, 1]))) not valid;

alter table "public"."ai_logs" validate constraint "ai_logs_rating_check";

alter table "public"."ai_logs" add constraint "ai_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."ai_logs" validate constraint "ai_logs_user_id_fkey";

alter table "public"."clubs" add constraint "clubs_slug_key" UNIQUE using index "clubs_slug_key";

alter table "public"."fixtures" add constraint "fixtures_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE not valid;

alter table "public"."fixtures" validate constraint "fixtures_team_id_fkey";

alter table "public"."match_reports" add constraint "match_reports_fixture_id_fkey" FOREIGN KEY (fixture_id) REFERENCES public.fixtures(id) not valid;

alter table "public"."match_reports" validate constraint "match_reports_fixture_id_fkey";

alter table "public"."match_reports" add constraint "match_reports_fixture_id_key" UNIQUE using index "match_reports_fixture_id_key";

alter table "public"."match_squads" add constraint "fk_player" FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE CASCADE not valid;

alter table "public"."match_squads" validate constraint "fk_player";

alter table "public"."players" add constraint "players_default_team_id_fkey" FOREIGN KEY (default_team_id) REFERENCES public.teams(id) ON DELETE SET NULL not valid;

alter table "public"."players" validate constraint "players_default_team_id_fkey";

alter table "public"."players" add constraint "players_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."players" validate constraint "players_user_id_fkey";

alter table "public"."players" add constraint "unique_club_user" UNIQUE using index "unique_club_user";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."transactions" add constraint "transactions_fixture_id_fkey" FOREIGN KEY (fixture_id) REFERENCES public.fixtures(id) ON DELETE SET NULL not valid;

alter table "public"."transactions" validate constraint "transactions_fixture_id_fkey";

alter table "public"."transactions" add constraint "transactions_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE SET NULL not valid;

alter table "public"."transactions" validate constraint "transactions_player_id_fkey";

alter table "public"."transactions" add constraint "transactions_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL not valid;

alter table "public"."transactions" validate constraint "transactions_team_id_fkey";

alter table "public"."transactions" add constraint "transactions_type_check" CHECK ((transaction_type = ANY (ARRAY['payment'::text, 'fee'::text, 'expense'::text]))) not valid;

alter table "public"."transactions" validate constraint "transactions_type_check";

alter table "public"."user_roles" add constraint "user_roles_club_id_fkey" FOREIGN KEY (club_id) REFERENCES public.clubs(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_club_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_role_check" CHECK ((role = ANY (ARRAY['super_admin'::text, 'club_admin'::text, 'team_admin'::text, 'player'::text]))) not valid;

alter table "public"."user_roles" validate constraint "user_roles_role_check";

alter table "public"."user_roles" add constraint "user_roles_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_team_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";

alter table "public"."users_deprecated_april2026" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) not valid;

alter table "public"."users_deprecated_april2026" validate constraint "users_auth_id_fkey";

alter table "public"."users_deprecated_april2026" add constraint "users_role_check" CHECK ((role = ANY (ARRAY['admin'::text, 'captain'::text]))) not valid;

alter table "public"."users_deprecated_april2026" validate constraint "users_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_super_admin()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin'
  );
$function$
;

grant delete on table "public"."ai_logs" to "anon";

grant insert on table "public"."ai_logs" to "anon";

grant references on table "public"."ai_logs" to "anon";

grant select on table "public"."ai_logs" to "anon";

grant trigger on table "public"."ai_logs" to "anon";

grant truncate on table "public"."ai_logs" to "anon";

grant update on table "public"."ai_logs" to "anon";

grant delete on table "public"."ai_logs" to "authenticated";

grant insert on table "public"."ai_logs" to "authenticated";

grant references on table "public"."ai_logs" to "authenticated";

grant select on table "public"."ai_logs" to "authenticated";

grant trigger on table "public"."ai_logs" to "authenticated";

grant truncate on table "public"."ai_logs" to "authenticated";

grant update on table "public"."ai_logs" to "authenticated";

grant delete on table "public"."ai_logs" to "service_role";

grant insert on table "public"."ai_logs" to "service_role";

grant references on table "public"."ai_logs" to "service_role";

grant select on table "public"."ai_logs" to "service_role";

grant trigger on table "public"."ai_logs" to "service_role";

grant truncate on table "public"."ai_logs" to "service_role";

grant update on table "public"."ai_logs" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."fixtures" to "anon";

grant insert on table "public"."fixtures" to "anon";

grant references on table "public"."fixtures" to "anon";

grant select on table "public"."fixtures" to "anon";

grant trigger on table "public"."fixtures" to "anon";

grant truncate on table "public"."fixtures" to "anon";

grant update on table "public"."fixtures" to "anon";

grant delete on table "public"."fixtures" to "authenticated";

grant insert on table "public"."fixtures" to "authenticated";

grant references on table "public"."fixtures" to "authenticated";

grant select on table "public"."fixtures" to "authenticated";

grant trigger on table "public"."fixtures" to "authenticated";

grant truncate on table "public"."fixtures" to "authenticated";

grant update on table "public"."fixtures" to "authenticated";

grant delete on table "public"."fixtures" to "service_role";

grant insert on table "public"."fixtures" to "service_role";

grant references on table "public"."fixtures" to "service_role";

grant select on table "public"."fixtures" to "service_role";

grant trigger on table "public"."fixtures" to "service_role";

grant truncate on table "public"."fixtures" to "service_role";

grant update on table "public"."fixtures" to "service_role";

grant delete on table "public"."match_reports" to "anon";

grant insert on table "public"."match_reports" to "anon";

grant references on table "public"."match_reports" to "anon";

grant select on table "public"."match_reports" to "anon";

grant trigger on table "public"."match_reports" to "anon";

grant truncate on table "public"."match_reports" to "anon";

grant update on table "public"."match_reports" to "anon";

grant delete on table "public"."match_reports" to "authenticated";

grant insert on table "public"."match_reports" to "authenticated";

grant references on table "public"."match_reports" to "authenticated";

grant select on table "public"."match_reports" to "authenticated";

grant trigger on table "public"."match_reports" to "authenticated";

grant truncate on table "public"."match_reports" to "authenticated";

grant update on table "public"."match_reports" to "authenticated";

grant delete on table "public"."match_reports" to "service_role";

grant insert on table "public"."match_reports" to "service_role";

grant references on table "public"."match_reports" to "service_role";

grant select on table "public"."match_reports" to "service_role";

grant trigger on table "public"."match_reports" to "service_role";

grant truncate on table "public"."match_reports" to "service_role";

grant update on table "public"."match_reports" to "service_role";

grant delete on table "public"."match_squads" to "anon";

grant insert on table "public"."match_squads" to "anon";

grant references on table "public"."match_squads" to "anon";

grant select on table "public"."match_squads" to "anon";

grant trigger on table "public"."match_squads" to "anon";

grant truncate on table "public"."match_squads" to "anon";

grant update on table "public"."match_squads" to "anon";

grant delete on table "public"."match_squads" to "authenticated";

grant insert on table "public"."match_squads" to "authenticated";

grant references on table "public"."match_squads" to "authenticated";

grant select on table "public"."match_squads" to "authenticated";

grant trigger on table "public"."match_squads" to "authenticated";

grant truncate on table "public"."match_squads" to "authenticated";

grant update on table "public"."match_squads" to "authenticated";

grant delete on table "public"."match_squads" to "service_role";

grant insert on table "public"."match_squads" to "service_role";

grant references on table "public"."match_squads" to "service_role";

grant select on table "public"."match_squads" to "service_role";

grant trigger on table "public"."match_squads" to "service_role";

grant truncate on table "public"."match_squads" to "service_role";

grant update on table "public"."match_squads" to "service_role";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."transactions" to "anon";

grant insert on table "public"."transactions" to "anon";

grant references on table "public"."transactions" to "anon";

grant select on table "public"."transactions" to "anon";

grant trigger on table "public"."transactions" to "anon";

grant truncate on table "public"."transactions" to "anon";

grant update on table "public"."transactions" to "anon";

grant delete on table "public"."transactions" to "authenticated";

grant insert on table "public"."transactions" to "authenticated";

grant references on table "public"."transactions" to "authenticated";

grant select on table "public"."transactions" to "authenticated";

grant trigger on table "public"."transactions" to "authenticated";

grant truncate on table "public"."transactions" to "authenticated";

grant update on table "public"."transactions" to "authenticated";

grant delete on table "public"."transactions" to "service_role";

grant insert on table "public"."transactions" to "service_role";

grant references on table "public"."transactions" to "service_role";

grant select on table "public"."transactions" to "service_role";

grant trigger on table "public"."transactions" to "service_role";

grant truncate on table "public"."transactions" to "service_role";

grant update on table "public"."transactions" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."users_deprecated_april2026" to "anon";

grant insert on table "public"."users_deprecated_april2026" to "anon";

grant references on table "public"."users_deprecated_april2026" to "anon";

grant select on table "public"."users_deprecated_april2026" to "anon";

grant trigger on table "public"."users_deprecated_april2026" to "anon";

grant truncate on table "public"."users_deprecated_april2026" to "anon";

grant update on table "public"."users_deprecated_april2026" to "anon";

grant delete on table "public"."users_deprecated_april2026" to "authenticated";

grant insert on table "public"."users_deprecated_april2026" to "authenticated";

grant references on table "public"."users_deprecated_april2026" to "authenticated";

grant select on table "public"."users_deprecated_april2026" to "authenticated";

grant trigger on table "public"."users_deprecated_april2026" to "authenticated";

grant truncate on table "public"."users_deprecated_april2026" to "authenticated";

grant update on table "public"."users_deprecated_april2026" to "authenticated";

grant delete on table "public"."users_deprecated_april2026" to "service_role";

grant insert on table "public"."users_deprecated_april2026" to "service_role";

grant references on table "public"."users_deprecated_april2026" to "service_role";

grant select on table "public"."users_deprecated_april2026" to "service_role";

grant trigger on table "public"."users_deprecated_april2026" to "service_role";

grant truncate on table "public"."users_deprecated_april2026" to "service_role";

grant update on table "public"."users_deprecated_april2026" to "service_role";


  create policy "Users can insert their own AI logs"
  on "public"."ai_logs"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "Users can view their own AI logs"
  on "public"."ai_logs"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "Admins can update clubs"
  on "public"."clubs"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = ANY (ARRAY['super_admin'::text, 'club_admin'::text])) AND ((user_roles.club_id IS NULL) OR (user_roles.club_id = clubs.id))))));



  create policy "Authenticated users can view clubs"
  on "public"."clubs"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Clubs are viewable by everyone"
  on "public"."clubs"
  as permissive
  for select
  to public
using (true);



  create policy "Super admins can insert clubs"
  on "public"."clubs"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'super_admin'::text)))));



  create policy "Admins can manage fixtures"
  on "public"."fixtures"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.teams t
     JOIN public.user_roles ur ON (((ur.club_id = t.club_id) OR (ur.role = 'super_admin'::text))))
  WHERE ((t.id = fixtures.team_id) AND ((ur.user_id = auth.uid()) OR (ur.email = (auth.jwt() ->> 'email'::text))) AND (ur.role = ANY (ARRAY['super_admin'::text, 'club_admin'::text]))))));



  create policy "Authenticated users can view fixtures"
  on "public"."fixtures"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admins can manage match squads"
  on "public"."match_squads"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM ((public.fixtures f
     JOIN public.teams t ON ((t.id = f.team_id)))
     JOIN public.user_roles ur ON (((ur.club_id = t.club_id) OR (ur.role = 'super_admin'::text))))
  WHERE ((f.id = match_squads.fixture_id) AND ((ur.user_id = auth.uid()) OR (ur.email = (auth.jwt() ->> 'email'::text))) AND (ur.role = ANY (ARRAY['super_admin'::text, 'club_admin'::text]))))));



  create policy "Authenticated users can view match squads"
  on "public"."match_squads"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admins can manage players"
  on "public"."players"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = ANY (ARRAY['super_admin'::text, 'club_admin'::text])) AND ((user_roles.club_id IS NULL) OR (user_roles.club_id = players.club_id))))));



  create policy "Authenticated users can view players"
  on "public"."players"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Profiles are viewable by club members"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Super admins can see all profiles"
  on "public"."profiles"
  as permissive
  for select
  to public
using (public.is_super_admin());



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id));



  create policy "Users can view own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "Users can view profiles"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Admins can manage teams"
  on "public"."teams"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = ANY (ARRAY['super_admin'::text, 'club_admin'::text])) AND ((user_roles.club_id IS NULL) OR (user_roles.club_id = teams.club_id))))));



  create policy "Authenticated users can view teams"
  on "public"."teams"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Captains can create transactions for their team"
  on "public"."transactions"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'team_admin'::text) AND (user_roles.team_id = transactions.team_id)))));



  create policy "Captains can view transactions for their team"
  on "public"."transactions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'team_admin'::text) AND (user_roles.team_id = transactions.team_id)))));



  create policy "Club Admins have full CRUD for their club"
  on "public"."transactions"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'club_admin'::text) AND (user_roles.club_id = transactions.club_id)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'club_admin'::text) AND (user_roles.club_id = transactions.club_id)))));



  create policy "Players can view their own transaction history"
  on "public"."transactions"
  as permissive
  for select
  to authenticated
using ((player_id = auth.uid()));



  create policy "Super Admins have full CRUD on transactions"
  on "public"."transactions"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'super_admin'::text)))))
with check ((EXISTS ( SELECT 1
   FROM public.user_roles
  WHERE (((user_roles.user_id = auth.uid()) OR (user_roles.email = (auth.jwt() ->> 'email'::text))) AND (user_roles.role = 'super_admin'::text)))));



  create policy "Enable delete for authenticated users"
  on "public"."user_roles"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Users can read roles"
  on "public"."user_roles"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Admin Delete Access"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'logos'::text));



  create policy "Admin Update Access"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'logos'::text));



  create policy "Admin Upload Access"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'logos'::text));



  create policy "Give users authenticated access to folder dbrwzi_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'squad-graphics'::text));



  create policy "Squad Graphics Auth Access"
  on "storage"."objects"
  as permissive
  for all
  to authenticated
using ((bucket_id = 'squad-graphics'::text))
with check ((bucket_id = 'squad-graphics'::text));



  create policy "Squad Graphics Public View"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'squad-graphics'::text));



